"""Scientific report builder (V2 roadmap M3.3, feature F11).

Assembles already-computed parts -- a publication figure (F6), the
scenario stats (summary_stats), the deterministic auto-summary prose
(auto_summary), and a provenance block (figure_export) -- into one
self-contained HTML document (figures embedded as base64 data URIs, so a
single file is shareable). A print stylesheet makes browser "Print to
PDF" produce a clean page, per the roadmap ("PDF via print stylesheet").

Pure string assembly, Qt-free and testable: the caller (MainWindow)
renders the figure PNG bytes and gathers the stats/prose/provenance; this
module only lays them out.
"""

from __future__ import annotations

import base64
import html

# (attribute, label, unit, format) for the scenario stats table. Mirrors
# the experiment browser's own columns so a report never disagrees with
# what the browser showed.
_STAT_ROWS = [
    ("max_temp_c", "Peak temperature", "°C", "{:.1f}"),
    ("time_to_100c_s", "Time to 100 °C", "s", "{:.1f}"),
    ("time_to_300c_s", "Time to 300 °C", "s", "{:.1f}"),
    ("time_to_600c_s", "Time to 600 °C", "s", "{:.1f}"),
    ("mean_upper_temp_c", "Mean upper-region temperature", "°C", "{:.1f}"),
    ("peak_hrr_kw", "Peak HRR", "kW", "{:.2f}"),
    ("total_energy_kj", "Total energy released", "kJ", "{:.1f}"),
    ("growth_alpha_kw_s2", "Fire-growth α", "kW/s²", "{:.2g}"),
    ("layer_min_height_m", "Minimum smoke-layer height", "m", "{:.2f}"),
    ("time_to_untenable_s", "Time to untenable heat", "s", "{:.1f}"),
]

_STYLE = """
body { font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif;
       color: #1a1a1a; max-width: 820px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
h1 { font-size: 1.5rem; margin-bottom: 0.2rem; }
h2 { font-size: 1.1rem; margin-top: 1.6rem; border-bottom: 1px solid #ddd; padding-bottom: 0.2rem; }
.prose { background: #f6f7f9; border-left: 3px solid #888; padding: 0.6rem 0.9rem; border-radius: 4px; }
table { border-collapse: collapse; width: 100%; margin: 0.6rem 0; font-size: 0.92rem; }
th, td { text-align: left; padding: 0.35rem 0.6rem; border-bottom: 1px solid #eee; }
th { background: #f0f1f3; }
td.num { text-align: right; font-variant-numeric: tabular-nums; }
img { max-width: 100%; height: auto; border: 1px solid #eee; border-radius: 4px; }
.provenance { font-size: 0.78rem; color: #666; background: #fafafa; padding: 0.5rem 0.7rem;
              border-radius: 4px; white-space: pre-wrap; }
footer { margin-top: 2rem; font-size: 0.75rem; color: #999; }
@media print { body { margin: 0; max-width: none; } h2 { page-break-after: avoid; }
                img, table { page-break-inside: avoid; } }
"""


def _esc(text) -> str:
    return html.escape(str(text))


def _fmt(summary, attr, spec) -> str:
    value = getattr(summary, attr, None)
    if value is None:
        return "n/a"
    return spec.format(value)


def _png_data_uri(png_bytes: bytes) -> str:
    return "data:image/png;base64," + base64.b64encode(png_bytes).decode("ascii")


def _figure_block(png_bytes: bytes, caption: str) -> str:
    if not png_bytes:
        return ""
    return (f'<figure><img alt="{_esc(caption)}" src="{_png_data_uri(png_bytes)}"/>'
            f'<figcaption style="font-size:0.82rem;color:#666">{_esc(caption)}</figcaption></figure>')


def _stats_table_single(summary) -> str:
    rows = "".join(
        f"<tr><th>{_esc(label)}</th><td class='num'>{_esc(_fmt(summary, attr, spec))}</td>"
        f"<td>{_esc(unit)}</td></tr>"
        for attr, label, unit, spec in _STAT_ROWS)
    return f"<table><thead><tr><th>Metric</th><th>Value</th><th>Unit</th></tr></thead><tbody>{rows}</tbody></table>"


def _stats_table_compare(summary_a, summary_b, label_a, label_b) -> str:
    rows = "".join(
        f"<tr><th>{_esc(label)}</th><td class='num'>{_esc(_fmt(summary_a, attr, spec))}</td>"
        f"<td class='num'>{_esc(_fmt(summary_b, attr, spec))}</td><td>{_esc(unit)}</td></tr>"
        for attr, label, unit, spec in _STAT_ROWS)
    return (f"<table><thead><tr><th>Metric</th><th>{_esc(label_a)}</th><th>{_esc(label_b)}</th>"
            f"<th>Unit</th></tr></thead><tbody>{rows}</tbody></table>")


def _document(title: str, body: str) -> str:
    return (f"<!doctype html><html><head><meta charset='utf-8'>"
            f"<title>{_esc(title)}</title><style>{_STYLE}</style></head>"
            f"<body>{body}"
            f"<footer>Generated by FDS Visualizer · numbers are computed from simulation "
            f"output, prose is templated (no generated content).</footer></body></html>")


def build_scenario_report(entry, summary, summary_text: str, figure_png: bytes,
                          provenance: str) -> str:
    """Self-contained HTML report for one scenario."""
    body = (
        f"<h1>Scenario report — {_esc(entry.folder)}</h1>"
        f"<h2>Summary</h2><p class='prose'>{_esc(summary_text)}</p>"
        f"<h2>Field</h2>{_figure_block(figure_png, 'Temperature at the peak-temperature frame.')}"
        f"<h2>Statistics</h2>{_stats_table_single(summary)}"
        f"<h2>Provenance</h2><div class='provenance'>{_esc(provenance)}</div>")
    return _document(f"Scenario report — {entry.folder}", body)


def _differences_block(differences: list) -> str:
    if not differences:
        return ""
    items = "".join(f"<li>{_esc(d)}</li>" for d in differences)
    return f"<h2>Key differences</h2><ul>{items}</ul>"


def build_comparison_report(entry_a, entry_b, summary_a, summary_b,
                            summary_text_a: str, summary_text_b: str,
                            diff_figure_png: bytes, provenance_a: str,
                            provenance_b: str, differences: list = None) -> str:
    """Self-contained HTML A-vs-B comparison report. `differences` (V3-M3)
    is the semantic-diff engine's ranked statements, rendered as a "Key
    differences" list above the raw statistics."""
    body = (
        f"<h1>Comparison report — {_esc(entry_a.folder)} vs {_esc(entry_b.folder)}</h1>"
        f"<h2>Difference field (A − B)</h2>"
        f"{_figure_block(diff_figure_png, f'{entry_a.folder} minus {entry_b.folder}, temperature.')}"
        f"{_differences_block(differences)}"
        f"<h2>Statistics</h2>{_stats_table_compare(summary_a, summary_b, entry_a.folder, entry_b.folder)}"
        f"<h2>{_esc(entry_a.folder)}</h2><p class='prose'>{_esc(summary_text_a)}</p>"
        f"<h2>{_esc(entry_b.folder)}</h2><p class='prose'>{_esc(summary_text_b)}</p>"
        f"<h2>Provenance</h2>"
        f"<div class='provenance'>A: {_esc(provenance_a)}\nB: {_esc(provenance_b)}</div>")
    return _document(f"Comparison — {entry_a.folder} vs {entry_b.folder}", body)


def write_report(path: str, html_text: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(html_text)
